/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/volscape.glb -o src/Volspace.jsx -r public 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/volscape.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials.material}
        position={[-0.616, 0.123, -5.636]}
        rotation={[-0.436, 0, 0]}
        scale={0.009}
      />
    </group>
  );
}

useGLTF.preload('/volscape.glb');
