import { useCodeStore } from '../stores';
import {
  getBranchRef,
  createBranchRef,
  createFileOnBranch,
  getFileContents,
} from './githubIssuesService';

export async function pushCodeToGitHub(codeBlock) {
  const { githubConnected, repoOwner, repoName, selectedRepo, selectedBranch } = useCodeStore.getState();
  if (!githubConnected || !selectedRepo) {
    return { ok: false, error: 'GitHub not connected or no repo selected' };
  }

  const owner = repoOwner || selectedRepo?.owner?.login;
  const repo = repoName || selectedRepo?.name;
  if (!owner || !repo) {
    return { ok: false, error: 'Repo owner/name not available' };
  }

  const token = useCodeStore.getState().githubToken;
  if (!token) {
    return { ok: false, error: 'GitHub token not available' };
  }

  const branch = selectedBranch || 'main';
  useCodeStore.getState().setPushStatus('pushing');

  try {
    let sha = null;
    try {
      const existing = await getFileContents(token, owner, repo, codeBlock.filePath, branch);
      if (existing.ok) {
        sha = existing.data.sha;
      }
    } catch {
      // file doesn't exist yet — sha stays null, will create new file
    }

    const message = `Auto-commit: ${codeBlock.filePath}\n\nGenerated by Hoverchart Code mode`;
    const result = await createFileOnBranch(
      token, owner, repo, codeBlock.filePath, codeBlock.code, branch, message, sha
    );

    if (result.ok) {
      useCodeStore.getState().setPushStatus('success');
    } else {
      useCodeStore.getState().setPushStatus('error');
    }

    return result;
  } catch (error) {
    useCodeStore.getState().setPushStatus('error');
    return { ok: false, error: error.message };
  }
}

export async function connectRepo(token, repo) {
  useCodeStore.getState().setGithubToken(token);
  useCodeStore.getState().setSelectedRepo(repo);
  useCodeStore.getState().setGithubConnected(true);

  const owner = repo.owner?.login;
  const name = repo.name;

  const mainRef = await getBranchRef(token, owner, name, 'main');
  if (mainRef.ok) {
    useCodeStore.getState().setRepoOwner(owner);
    useCodeStore.getState().setRepoName(name);
    useCodeStore.getState().setSelectedBranch('main');
    return { ok: true, data: mainRef.data };
  }

  const defaultBranch = repo.default_branch || 'master';
  const fallbackRef = await getBranchRef(token, owner, name, defaultBranch);
  if (fallbackRef.ok) {
    useCodeStore.getState().setRepoOwner(owner);
    useCodeStore.getState().setRepoName(name);
    useCodeStore.getState().setSelectedBranch(defaultBranch);
    return { ok: true, data: fallbackRef.data };
  }

  return { ok: false, error: 'Could not find any branch in repository' };
}

export async function listBranches(token, owner, repo) {
  const response = await fetch(
    `https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/branches?per_page=100`,
    {
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3+json',
      },
    }
  );

  if (!response.ok) {
    return { ok: false, data: null, error: `${response.status}: ${response.statusText}` };
  }

  const data = await response.json();
  return { ok: true, data: data.map(b => b.name), error: null };
}

export async function switchBranch(token, owner, repo, branch) {
  const ref = await getBranchRef(token, owner, repo, branch);
  if (!ref.ok) {
    return { ok: false, error: ref.error || 'Branch not found' };
  }

  useCodeStore.getState().setSelectedBranch(branch);
  return { ok: true, data: ref.data };
}

export async function createNewBranch(token, owner, repo, newBranch, sourceBranch = 'main') {
  const sourceRef = await getBranchRef(token, owner, repo, sourceBranch);
  if (!sourceRef.ok) {
    return { ok: false, error: `Source branch '${sourceBranch}' not found: ${sourceRef.error}` };
  }

  const sha = sourceRef.data.object.sha;
  const result = await createBranchRef(token, owner, repo, newBranch, sha);
  if (result.ok) {
    useCodeStore.getState().setSelectedBranch(newBranch);
    return { ok: true, data: result.data };
  }
  return result;
}
