/**
 * wasmKernels.js
 *
 * Lazy loader and convenience wrappers for the hoverchart Rust/Wasm compute
 * kernels.  All functions degrade gracefully to no-ops / null returns when
 * the wasm module is unavailable (e.g. in workers that haven't initialised it
 * yet, or browsers that block wasm).
 *
 * Public API
 * ----------
 *   initWasmKernels()           — async; call once at app startup / worker init
 *   isWasmReady()               — sync; true once initWasmKernels() resolves
 *
 *   fillEdgeBuffers(...)        — wraps Rust `fill_edge_buffers`
 *   getScratchStartView(len)    — zero-copy Float32Array view of start buffer
 *   getScratchEndView(len)      — zero-copy Float32Array view of end buffer
 *   getScratchColorView(len)    — zero-copy Float32Array view of color buffer
 *
 *   computeLodUpdates(...)      — wraps Rust `compute_lod_updates`
 *   frustumCullConnections(...) — wraps Rust `frustum_cull_connections`
 *
 * The wasm module is loaded from `../wasm/pkg/hoverchart_wasm.js` which is
 * committed to the repository (generated by `npm run build:wasm`).
 * `vite-plugin-wasm` + `vite-plugin-top-level-await` handle the bundling.
 */

// Module state ---------------------------------------------------------------
let _wasm = null;          // wasm-bindgen module export object
let _initPromise = null;   // singleton promise; prevents double-init
let _ready = false;

// ---------------------------------------------------------------------------
// Initialisation
// ---------------------------------------------------------------------------

/**
 * Initialise the wasm module.  Safe to call multiple times; only the first
 * call triggers loading — subsequent calls return the same promise.
 *
 * @returns {Promise<void>}
 */
export async function initWasmKernels() {
  if (_ready) return;
  if (_initPromise) return _initPromise;

  _initPromise = (async () => {
    try {
      // Dynamic import so the wasm file is only fetched when actually needed.
      // vite-plugin-wasm transforms this to a proper asset import.
      const mod = await import('../wasm/pkg/hoverchart_wasm.js');
      // wasm-pack --target web generates an `default` export that is the
      // init() function; calling it finalises the wasm module.
      await mod.default();
      _wasm = mod;
      _ready = true;
    } catch (err) {
      // Non-fatal: the renderers fall back to the existing JS implementations.
      console.warn('[wasmKernels] wasm init failed, falling back to JS:', err);
    }
  })();

  return _initPromise;
}

/**
 * @returns {boolean} true when the wasm module is loaded and ready to use.
 */
export function isWasmReady() {
  return _ready;
}

// ---------------------------------------------------------------------------
// Edge buffer fill kernel
// ---------------------------------------------------------------------------

/**
 * Fill the wasm scratch buffers with transformed edge vertices for N objects.
 *
 * This is a thin wrapper around the Rust `fill_edge_buffers` function.
 * After calling this, retrieve the results with `getScratchStartView`,
 * `getScratchEndView`, and `getScratchColorView`.
 *
 * Returns `false` if wasm is not ready (caller should use the JS fallback).
 *
 * @param {Float32Array} positions       — N×3: [x0,y0,z0, x1,y1,z1, …]
 * @param {Float32Array} scales          — N×3: [sx0,sy0,sz0, …]
 * @param {Float32Array} colorsRgb       — N×3: [r0,g0,b0, …] (0–1 range)
 * @param {Uint8Array}   visible         — N: 0=hidden (zero-out), 1=write
 * @param {Float32Array} templateStart   — E×3: local-space edge start points
 * @param {Float32Array} templateEnd     — E×3: local-space edge end points
 * @param {number}       edgesPerObject  — edges per object (12 / 30 / 6)
 * @returns {boolean}
 */
export function fillEdgeBuffers(
  positions,
  scales,
  colorsRgb,
  visible,
  templateStart,
  templateEnd,
  edgesPerObject,
) {
  if (!_ready) return false;
  _wasm.fill_edge_buffers(
    positions,
    scales,
    colorsRgb,
    visible,
    templateStart,
    templateEnd,
    edgesPerObject,
  );
  return true;
}

/**
 * Return a zero-copy Float32Array view over the instanceStart scratch buffer
 * that was written by the last `fillEdgeBuffers` call.
 *
 * The view is valid until any Rust code triggers a wasm heap reallocation,
 * which in practice means it must be consumed before the next wasm call.
 * Callers typically call `instanceStartAttr.array.set(view)` immediately.
 *
 * @param {number} len — number of floats to expose (count * edgesPerObject * 3)
 * @returns {Float32Array}
 */
export function getScratchStartView(len) {
  if (!_ready) return null;
  return _wasm.get_scratch_start_view(len);
}

/** @param {number} len @returns {Float32Array|null} */
export function getScratchEndView(len) {
  if (!_ready) return null;
  return _wasm.get_scratch_end_view(len);
}

/** @param {number} len @returns {Float32Array|null} */
export function getScratchColorView(len) {
  if (!_ready) return null;
  return _wasm.get_scratch_color_view(len);
}

// ---------------------------------------------------------------------------
// LOD computation kernel  (used inside spatialIndexWorker)
// ---------------------------------------------------------------------------

/**
 * Compute per-object LOD levels and return only the changed entries.
 *
 * @param {Float32Array} positions       — N×3 flat position array
 * @param {Uint8Array}   metaFlags       — N bytes (bit0=isContainer, bit1=isParent)
 * @param {Uint8Array}   currentLevels   — N bytes: current LOD level per object
 * @param {number}       cx              — camera X
 * @param {number}       cy              — camera Y
 * @param {number}       cz              — camera Z
 * @param {number}       childFullSq     — squared distance: child FULL threshold
 * @param {number}       childMediumSq   — squared distance: child MEDIUM threshold
 * @param {number}       parentFullSq    — squared distance: parent FULL threshold
 * @param {number}       parentMediumSq  — squared distance: parent MEDIUM threshold
 * @returns {Uint32Array|null}  interleaved [index, newLevel, …] or null if wasm unavailable
 */
export function computeLodUpdates(
  positions,
  metaFlags,
  currentLevels,
  cx,
  cy,
  cz,
  childFullSq,
  childMediumSq,
  parentFullSq,
  parentMediumSq,
) {
  if (!_ready) return null;
  return _wasm.compute_lod_updates(
    positions,
    metaFlags,
    currentLevels,
    cx, cy, cz,
    childFullSq, childMediumSq,
    parentFullSq, parentMediumSq,
  );
}

// ---------------------------------------------------------------------------
// Frustum-cull connections kernel  (used inside spatialIndexWorker)
// ---------------------------------------------------------------------------

/**
 * Test N connections against 6 frustum planes.
 *
 * @param {Float32Array} startPositions — conn_count×3 flat start-point array
 * @param {Float32Array} endPositions   — conn_count×3 flat end-point array;
 *                                        use NaN for missing/unknown endpoints
 * @param {Float32Array} planes         — 24 floats: [nx,ny,nz,d] × 6 planes
 * @returns {Uint8Array|null}  length conn_count: 1=visible, 0=hidden, or null if unavailable
 */
export function frustumCullConnections(startPositions, endPositions, planes) {
  if (!_ready) return null;
  return _wasm.frustum_cull_connections(startPositions, endPositions, planes);
}
